from typing import TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage
import operator

class AgentState(TypedDict):
    """
    State representing the current execution context of the Agent Friday agent.

    Attributes:
        messages: The sequence of chat messages (human, ai, tool).
        plan: The current plan generated by the planner node.
        next_step: The specific step to be executed next.
        pending_tool_calls: Tool calls that require human approval.
        approval_status: Status of the human gate ("pending", "approved", "denied").
        iterations: Executor LLM invocations for this run (loop budget).
        tool_log: Append-only log of executed tools for UI inspection.
    """
    messages: Annotated[Sequence[BaseMessage], operator.add]
    plan: str
    next_step: str
    pending_tool_calls: list[dict]
    approval_status: str
    iterations: int
    tool_log: Annotated[list[dict], operator.add]
